logging:
  level:
    com.example.userservice: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: nomal
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
